spring.application.name=eprescription
spring.datasource.url=jdbc:postgresql://localhost:5432/eprescription
spring.datasource.username=postgres
spring.datasource.password=neha015

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080